epdp_wasi_temp := "epdp-wasi-temp.wasm"
epdp_wasm := "policy.wasm"
target_arch_os := "wasm32-unknown-unknown"

compose: build-now-stub
    wasm-tools component new {{ epdp_wasm }} -o {{ epdp_wasi_temp }} --adapt ./env.wasm

build-now-stub:
    #!/usr/bin/env bash
    rustc -o env.wasm --target {{ target_arch_os }} --crate-type cdylib --edition=2021 \
     -C opt-level=z -C lto -C codegen-units=1 -C debuginfo=0  - <<EOF
    #[no_mangle]
    pub unsafe extern "C" fn now() -> u64 { 0 }
    EOF
