[package]
name = "http-proxy"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.203"
serde_json = "1.0.117"
wit-bindgen = { version = "0.24", features = ["default"] }
