name := "http_proxy.wasm"
target := join(justfile_directory(), "build", name)
output := "http-cerbos.wasm"

# to test in wasmtime
wasmtime-up:
    wash build --build-only
    wasm-tools compose ./build/{{ name }} -d ../epdp-wasi-adapter/build/epdp-wasi.wasm -o {{ output }}
    wasmtime serve --addr 0.0.0.0:8081 -S common {{ output }}

deploy:
    wash build
    wash app deploy ./wadm.yaml
